# SPDX-FileCopyrightText: Copyright (c) 2021-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT

[default]
extend-ignore-identifiers-re = [
  "repositor",        # valid literal, for example 'repositor + ies/y'
]
