# (The MIT License)
#
# Copyright (c) 2021-2025 Yegor Bugayenko
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the 'Software'), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
title: KaiCode.org
email: team@kaicode.org
description: >
  Annual Competition for Young Open Source Projects
baseurl: ""
url: "https://www.kaicode.org"
markdown: kramdown
author:
  name: "Yegor Bugayenko"
  email: yegor256@gmail.com
encoding: utf-8
timezone: Europe/Moscow
permalink: :year-:month-:day-:title.html
exclude:
  - README.md
  - Gemfile.lock
  - Gemfile
  - LICENSE.txt

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

feed:
  title: www.kaicode.org
  subtitle: Annual Competition for Young Open Source Projects
  path: rss.xml

sass:
  style: compressed
  deploy_style: compressed
  compile_in_place: false

breadcrumbs:
  - https://www.yegor256.com/2015/04/16/award.html: 2015
  - https://www.yegor256.com/2015/10/17/award-2016.html: 2016
  - https://www.yegor256.com/2016/10/23/award-2017.html: 2017
  - https://www.yegor256.com/2017/10/24/award-2018.html: 2018
  - https://www.yegor256.com/2018/09/30/award-2019.html: 2019
  - https://www.yegor256.com/2019/11/03/award-2020.html: 2020
  - /2024.html: 2024
  - /2025.html: 2025
